=== SolarHauks/CabinetInfirmier/data/xsd/actes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace='http://www.univ-grenoble-alpes.fr/l3miage/actes'
        xmlns:ci='http://www.univ-grenoble-alpes.fr/l3miage/actes'
        elementFormDefault = "qualified" >
    
    <element name="ngap" type="ci:NGAP"/>
    
    <!--*****************************       Implementation des Complex Type       *****************************-->
    
    <!-- Type NGAP  -->
    
    <!-- Un NGAP à une liste de types d'actes et une liste d'actes. -->
    <complexType name="NGAP">
        <sequence>
            <element name="types" type="ci:Types"/>
            <element name="actes" type="ci:Actes"/>
        </sequence>
    </complexType>
    
    <!-- Type Types -->
    
    <!-- Types est une liste comprenant les types d'actes. -->
    
    <complexType name="Types">
        <sequence>
            <element name="type" type="ci:Type" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <!-- Type Type  -->
    
    <!-- Un Type doit avoir un id et un nom. -->
    
    <element name="Type">
        <complexType>
            <simpleContent>
                <extension base="string">
                    <attribute name="id" type="ci:Chaine" use="required">
                </extension>
            </simpleContent>
        </complexType>
    </element>
    
    <!-- Type Actes -->
    
    <!-- Actes est une liste comprenant les information des actes. -->
    
    <complexType name="Actes">
        <sequence>
            <element name="acte" type="ci:Acte" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <!-- Type Acte  -->
    
    <!-- Un Acte doit avoir un id, un type, une clé, un coef et un nom. -->
    
    <complexType name="Acte">
        <sequence>
            <element name="nom" type="ci:Chaine"/>
        </sequence>
        <attribute name="id" type="ci:Chaine" use="required"/>
        <attribute name="type" type="ci:Chaine" use="required"/>
        <attribute name="clé" type="ci:Chaine" use="required"/>
        <attribute name="coef" type="ci:Nombre" use="required"/>
    </complexType>
    
    <!--*****************************       Implementation des Simple Type       *****************************-->
    
    <!-- Type Chaine -->
    
    <!-- Chaine est une chaine de caractère. -->
    
    <simpleType name="Chaine">
        <restriction base="string">
            <pattern value="[a-zA-Z0-9\s]+"/>
        </restriction>
    </simpleType>
    
    <!-- Type Nombre -->
    
    <!-- Un Nombre est un nombre à trois chiffres max. -->
    
    <simpleType name="Nombre">
        <restriction base="string">
            <pattern value="[0-9.]{0,3}"/>
        </restriction>
    </simpleType>
    
</schema>

=== SolarHauks/CabinetInfirmier/data/xml/actes.xml
<?xml version="1.0" encoding="UTF-8"?>
<ngap xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
      xmlns='http://www.univ-grenoble-alpes.fr/l3miage/actes' 
      xsi:schemaLocation='http://www.univ-grenoble-alpes.fr/l3miage/actes ../xsd/actes.xsd'>
    
    <!-- Description des types d'actes réalisables lors d'une visite médicale. Contient de plus les informations 
    nécessaires pour le calcul du montant de la facture de la visite-->
    
    <types>
        <type id="pi">prélèvements et injections</type>
        <type id="pc">pansements courants</type>
        <type id="pl">pansements lourds et complexes nécessitant des condition d’asepsie rigoureuse</type>
        <type id="sd">Soins infirmiers à domicile pour un patient, quel que soit son âge, en situation de dépendance 
            temporaire ou permanante.</type>
    </types>
    <actes>
        <acte id="101" type="pi" clé="AMI" coef="1.5">Prélèvement par ponction veineuse directe. </acte>
        <acte id="102" type="pi" clé="AMI" coef="5">Saignée. </acte>
        <acte id="103" type="pi" clé="AMI" coef="1">Prélèvement aseptique cutané ou de sécrétions muqueuses, prélèvement
            de selles ou d’urine pour examens sytologiques, bactériologiques, mycologiques. </acte>
        <!-- ...et plein d’autres actes -->
    </actes>
</ngap>
